config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/donate'

  post 'webhook(/:uid)', to: 'webhook#index'

  root 'home#index'
end

app/models/access_token.rb
# == Schema Information
#
# Table name: access_tokens
#
#  id            :integer          not null, primary key
#  uid           :string
#  access_token  :string
#  token_type    :string
#  expires_in    :string
#  refresh_token :string
#  scope         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class AccessToken < ApplicationRecord
  validates :uid, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:code]
      token_params = TraktService.get_token(params[:code], params[:username], request.base_url)
      token_params.merge!(created_at: nil, uid: SecureRandom.hex(10), username: params[:username])
      @token = AccessToken.new(token_params)
      @success = @token.save
      return render :auth
    end
  end

  def donate
  end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    payload = JSON.parse(params['payload'])

    access_token = AccessToken.where(uid: params[:uid]).first
    return unless payload['Account']['title'].downcase == access_token.username.downcase

    case payload['Metadata']['librarySectionType']
    when 'show'
      TraktService.submit_episode(payload['event'].gsub('media.', ''), payload, access_token)
    when 'movie'
      TraktService.submit_movie(payload['event'].gsub('media.', ''), payload, access_token)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/views/home/auth.html.erb
<% if @success %>
  <h2>Congratulations!</h2>
  <p>That was easy wasn't it?</p>

  <p>Here is your webhook URL:</p>

  <pre>
  <%= "#{request.base_url}/webhook/#{@token.uid}" %>
  </pre>

  <p>Now ask Plex to use it:</p>

  <ol>
    <li>Open up the <%= link_to 'Plex Webhooks Panel', 'https://app.plex.tv/desktop#!/account/webhooks', target: :blank %></li>
    <li>Click "Add Webhook"</li>
    <li>Paste the URL above and click save</li>
  </ol>

  <p>That's it! Get scrobblin'</p>
<% else %>
  <h1>Oh shit :(</h1>
  <p>Sorry, something went wrong. Try again?</p>
<% end %>

app/views/home/donate.html.erb
<h2>Donate</h3>

<p>If you like, you can donate bitcoin at the address below.</p>

<pre>1BtA1yEcpm4BBBXBCe5UnmJJnbg6VVdzXG</pre>

app/views/home/index.html.erb
<h2>This project has moved!</h3>

<p>Find it's new home at <a href="https://plaxt.astandke.com/">https://plaxt.astandke.com/</a>, updated to Trakt's new auth standards so your scrobbles won't randomly stop after 3 months!</p>

<p>Webhooks still pointing at this URL will continue to work for a short time, but you should create a new link at the new site ASAP!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plaxt</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <div class="header">
        <h1>Plex Webhooks for Trakt</h1>

        <div class="wrapper">
          <div class="grid1"><%= link_to image_tag('plex.png', width: '100%'), 'https://plex.tv' %></div>
          <div class="grid2"><%= image_tag 'heart.png', width: '100%' %></div>
          <div class="grid3"><%= link_to image_tag('trakt.png', width: '100%'), 'https://trakt.tv' %></div>
        </div>
      </div>

      <div class="main">
        <%= yield %>
      </div>

      <div class="foot">
        Made with <3 by <%= link_to 'Alex Standke', 'http://astandke.com/', target: :blank %>. All product names, logos, and brands are property of their respective owners.

        <span style="float:right"><%= link_to 'Fork me on Github', 'https://github.com/XanderStrike/plaxt' %>. <%= link_to 'Donate', home_donate_path %></span>
      </div>
    </div>

    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript %>
  </body>
</html>

app/views/webhook/index.html.erb
<h1>Webhook#index</h1>
<p>Find me in app/views/webhook/index.html.erb</p>